AplicationDoc: C:/SVN/00_DEMO/trunk/Firmware/Main/driver/ADCd_driver.c File Reference
ADCd_driver.c File Reference
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"
#include "ADCd_driver.h"
Functions
void ADCd_Init (void)
void ADC_Start (void)
void __attribute__ ((__interrupt__))
void storeADC (void)
void vApplicationTickHook (void)
Variables
xQueueHandle ADC_Que
xQueueHandle ADCBattery_Que
Function Documentation
void __attribute__ ((__interrupt__))
Definition at line 65 of file ADCd_driver.c.
References OFF, and storeADC().
void ADC_Start (void)
Definition at line 56 of file ADCd_driver.c.
References OFF, and ON.
Referenced by vApplicationTickHook().
void ADCd_Init (void)
Definition at line 39 of file ADCd_driver.c.
References ADC_CHANNELS, ADC_PINS, ADC_Que, ADC_SCAN, ADCBattery_Que, CH_SELECT, INT_SET, ON, and SAMPLE_TIME.
void storeADC (void)
Definition at line 74 of file ADCd_driver.c.
References ADC_Que, and ADCBattery_Que.
Referenced by __attribute__().
void vApplicationTickHook (void)
Definition at line 107 of file ADCd_driver.c.
References ADC_Start().
Variable Documentation
xQueueHandle ADC_Que
Definition at line 38 of file ADCd_driver.c.
Referenced by ADCd_Init(), and storeADC().
xQueueHandle ADCBattery_Que
Definition at line 38 of file ADCd_driver.c.
Referenced by ADCd_Init(), and storeADC().