AplicationDoc: C:/SVN/00_DEMO/trunk/Firmware/Main/driver/FLASH_driver.h File Reference
FLASH_driver.h File Reference
Data Structures
struct sLanguageItems
struct sAlarmItems
Macros
#define nWriteFlash 0x06;
#define nReadFlash 0x03;
#define MAX 150;
Enumerations
enum eLanguageItems {
Romana = 0, English, Francais, Deutsch,
Espanol, Turkce, Italino, Magyar,
Nederlands, Portugues
}
enum eAlarmItems { Fire = 0, Gase, Steam }
Functions
int getLanguageLine (char acLanguage[10])
int getAllarmSector (char acAlarm[5])
void write_Flash (char acAlarm[5], char acLanguage[10], unsigned char *pText, unsigned char ucTextLength)
void read_Flash (char acAlarm[5], char acLanguage[10])
Variables
struct sLanguageItems sLanguageItemsList []
struct sAlarmItems sAlarmItemsList []
Macro Definition Documentation
#define MAX 150;
Definition at line 86 of file FLASH_driver.h.
Referenced by read_Flash(), and write_Flash().
#define nReadFlash 0x03;
Definition at line 83 of file FLASH_driver.h.
Referenced by read_Flash().
#define nWriteFlash 0x06;
Definition at line 80 of file FLASH_driver.h.
Referenced by write_Flash().
Enumeration Type Documentation
enum eAlarmItems
Enumerator
Fire
Gase
Steam
Definition at line 18 of file FLASH_driver.h.
enum eLanguageItems
Enumerator
Romana
English
Francais
Deutsch
Espanol
Turkce
Italino
Magyar
Nederlands
Portugues
Definition at line 4 of file FLASH_driver.h.
Function Documentation
int getAllarmSector (char acAlarm[5])
Definition at line 92 of file FLASH_driver.c.
References Fire, Gase, sAlarmItems::id, sAlarmItems::pName, sAlarmItemsList, and Steam.
Referenced by read_Flash(), and write_Flash().
int getLanguageLine (char acLanguage[10])
Definition at line 38 of file FLASH_driver.c.
References Deutsch, English, Espanol, Francais, sLanguageItems::id, Italino, Magyar, Nederlands, sLanguageItems::pName, Portugues, Romana, sLanguageItemsList, and Turkce.
Referenced by read_Flash(), and write_Flash().
void read_Flash (char acAlarm[5], char acLanguage[10])
Definition at line 186 of file FLASH_driver.c.
References getAllarmSector(), getLanguageLine(), MAX, nReadFlash, SPI_read(), and SPI_write().
void write_Flash (char acAlarm[5], char acLanguage[10], unsigned char * pText, unsigned char ucTextLength)
Definition at line 127 of file FLASH_driver.c.
References getAllarmSector(), getLanguageLine(), MAX, nWriteFlash, and SPI_write().
Variable Documentation
struct sAlarmItems sAlarmItemsList[]
Initial value:
= {
        {"Fire", Fire},
        {"Gase", Gase},
        {"Steam", Steam}
}
Referenced by getAllarmSector().
struct sLanguageItems sLanguageItemsList[]
Initial value:
= {
        {"Romana", Romana},
        {"English", English},
        {"Francais", Francais},
        {"Deutsh", Deutsch},
        {"Espanol", Espanol},
        {"Turkce", Turkce},
        {"Italino", Italino},
        {"Magyar", Magyar},
        {"Nederlands", Nederlands},
        {"Portugues", Portugues}
}
Referenced by getLanguageLine().