AplicationDoc: C:/SVN/00_DEMO/trunk/Firmware/Main/driver/FLASH_driver.c File Reference
FLASH_driver.c File Reference
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"
#include "SPId_driver.h"
#include "FLASH_DRIVER.h"
Functions
int getLanguageLine (char acLanguage[10])
int getAllarmSector (char acAlarm[5])
void write_Flash (char acAlarm[5], char acLanguage[10], unsigned char *pText, unsigned char ucTextLength)
void read_Flash (char acAlarm[5], char acLanguage[10])
Function Documentation
int getAllarmSector (char acAlarm[5])
Definition at line 92 of file FLASH_driver.c.
References Fire, Gase, sAlarmItems::id, sAlarmItems::pName, sAlarmItemsList, and Steam.
Referenced by read_Flash(), and write_Flash().
int getLanguageLine (char acLanguage[10])
Definition at line 38 of file FLASH_driver.c.
References Deutsch, English, Espanol, Francais, sLanguageItems::id, Italino, Magyar, Nederlands, sLanguageItems::pName, Portugues, Romana, sLanguageItemsList, and Turkce.
Referenced by read_Flash(), and write_Flash().
void read_Flash (char acAlarm[5], char acLanguage[10])
Definition at line 186 of file FLASH_driver.c.
References getAllarmSector(), getLanguageLine(), MAX, nReadFlash, SPI_read(), and SPI_write().
void write_Flash (char acAlarm[5], char acLanguage[10], unsigned char * pText, unsigned char ucTextLength)
Definition at line 127 of file FLASH_driver.c.
References getAllarmSector(), getLanguageLine(), MAX, nWriteFlash, and SPI_write().