AplicationDoc: C:/SVN/00_DEMO/trunk/Firmware/Main/driver/GPIO_INITd_driver.h File Reference
GPIO_INITd_driver.h File Reference
Typedefs
typedef unsigned char u_char
typedef unsigned int u_int
Enumerations
enum SELECT { GPIO =0, Function =1 }
enum IO_direction { OUTPUT = 0, INPUT = 1 }
enum PORTS {
ePORTA = 0, ePORTB = 1, ePORTC = 2, ePORTD = 3,
ePORTE = 4, ePORTF = 5
}
enum PINS {
PIN0 = 0, PIN1 = 1, PIN2 = 2, PIN3 = 3,
PIN4 = 4, PIN5 = 5, PIN6 = 6, PIN7 = 7,
PIN8 = 8, PIN9 = 9, PIN10 = 10, PIN11 = 11,
PIN12 = 12, PIN13 = 13, PIN14 = 14, PIN15 = 15
}
Functions
void SET_PIN_MODE (u_char pin, u_char port, u_char mode, u_char direction)
void SET_IO_PIN_DIRECTION (u_char GPIO_pin, u_char GPIO_port, u_char GPIO_direction)
u_char GET_IO_PIN_STATE (u_char GPIO_pin, u_char GPIO_port)
void SET_IO_PIN (u_char GPIO_pin, u_char GPIO_port, u_char GPIO_value)
u_char GET_IO_PIN (u_char GPIO_pin, u_char GPIO_port)
Typedef Documentation
typedef unsigned char u_char
Definition at line 15 of file GPIO_INITd_driver.h.
typedef unsigned int u_int
Definition at line 16 of file GPIO_INITd_driver.h.
Enumeration Type Documentation
enum IO_direction
Enumerator
OUTPUT
INPUT
Definition at line 87 of file GPIO_INITd_driver.h.
enum PINS
Enumerator
PIN0
PIN1
PIN2
PIN3
PIN4
PIN5
PIN6
PIN7
PIN8
PIN9
PIN10
PIN11
PIN12
PIN13
PIN14
PIN15
Definition at line 101 of file GPIO_INITd_driver.h.
enum PORTS
Enumerator
ePORTA
ePORTB
ePORTC
ePORTD
ePORTE
ePORTF
Definition at line 92 of file GPIO_INITd_driver.h.
enum SELECT
Enumerator
GPIO
Function
Definition at line 82 of file GPIO_INITd_driver.h.
Function Documentation
u_char GET_IO_PIN (u_char GPIO_pin, u_char GPIO_port)
Definition at line 1234 of file GPIO_INITd_driver.c.
References ePORTB, ePORTC, ePORTD, ePORTE, ePORTF, PIN0, PIN1, PIN10, PIN11, PIN12, PIN13, PIN14, PIN15, PIN4, PIN5, PIN6, PIN7, PIN8, and PIN9.
u_char GET_IO_PIN_STATE (u_char GPIO_pin, u_char GPIO_port)
To check if the state of a PIN call GET_IO_PIN_STATE() with the next variables: GPIO_pin = PIN0 - PIN15 The PIN you want to see ** GPIO_port = ePORTA - ePORTE The PORT you want to see ** Function will return the valuea read on TRISx ** IO_return_state = 1 PIN IMPUT ** = 0 PIN OUTPUT
Definition at line 487 of file GPIO_INITd_driver.c.
References ePORTB, ePORTC, ePORTD, ePORTE, ePORTF, PIN0, PIN1, PIN10, PIN11, PIN12, PIN13, PIN14, PIN15, PIN4, PIN5, PIN6, PIN7, PIN8, and PIN9.
void SET_IO_PIN (u_char GPIO_pin, u_char GPIO_port, u_char GPIO_value)
Definition at line 861 of file GPIO_INITd_driver.c.
References ePORTB, ePORTC, ePORTD, ePORTE, ePORTF, PIN0, PIN1, PIN10, PIN11, PIN12, PIN13, PIN14, PIN15, PIN4, PIN5, PIN6, PIN7, PIN8, and PIN9.
Referenced by Feed(), i2c_init(), LED(), ReceiveSemaphore_LED(), and WDT_Function().
void SET_IO_PIN_DIRECTION (u_char GPIO_pin, u_char GPIO_port, u_char GPIO_direction)
To set the state and the direction of a PIN call SET_PIN_DIRECTION() This function does not need to be called. Function is automatically called from: SET_PIN_MODE(u_char pin, u_char port, u_char mode, u_char direction) GPIO_pin = PIN0 - PIN15 Pinul pe care doriti sa il folositi ** GPIO_port = ePORTA - ePORTE Portul pe care doriti sa il folositi ** directon = INPUT ** = OUTPUT
Definition at line 59 of file GPIO_INITd_driver.c.
References ePORTB, ePORTC, ePORTD, ePORTE, ePORTF, INPUT, PIN0, PIN1, PIN10, PIN11, PIN12, PIN13, PIN14, PIN15, PIN2, PIN3, PIN4, PIN5, PIN6, PIN7, PIN8, and PIN9.
Referenced by SET_PIN_MODE().
void SET_PIN_MODE (u_char pin, u_char port, u_char mode, u_char direction)
To set the state and the direction of a PIN call SET_PIN_MODE() with the next variables: ** pin = PIN0 - PIN15 The PIN you want to use ** port = ePORTA - ePORTE The PORT you want to use ** mode = GPIO Set PIN as GPIO ** = Function Set PIN as implicit function ** directon = INPUT ** = OUTPUT
Definition at line 38 of file GPIO_INITd_driver.c.
References Function, GPIO, and SET_IO_PIN_DIRECTION().
Referenced by i2c_init(), LED(), ReceiveSemaphore_LED(), and WDT_Function().