AplicationDoc: C:/SVN/00_DEMO/trunk/Firmware/Main/driver/I2Cd_driver.c File Reference
I2Cd_driver.c File Reference
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"
#include "SPId_driver.h"
#include "i2c.h"
#include "GPIO_INITd_driver.h"
Macros
#define DELAY 1
#define DELAY10U 0.01
#define DELAY1U 0.001
#define DELAY100U 0.1
#define RESETTIME 30
Functions
void select_i2c (unsigned char i2c_select_value)
void i2c_init ()
void reset_i2c_bus ()
void i2c_start ()
void i2c_repStart ()
void i2c_stop ()
void send_i2c_byte (unsigned int data)
unsigned char read_i2c_byte ()
void I2CWrite (unsigned char address, unsigned char i2cWriteData)
unsigned char I2CRead (unsigned char address, unsigned char ack)
Variables
unsigned char i2cselected = 0
Macro Definition Documentation
#define DELAY 1
Definition at line 10 of file I2Cd_driver.c.
Referenced by i2c_repStart(), and i2c_start().
#define DELAY100U 0.1
Definition at line 13 of file I2Cd_driver.c.
Referenced by I2CRead().
#define DELAY10U 0.01
Definition at line 11 of file I2Cd_driver.c.
Referenced by i2c_init(), i2c_repStart(), i2c_start(), i2c_stop(), I2CRead(), I2CWrite(), and reset_i2c_bus().
#define DELAY1U 0.001
Definition at line 12 of file I2Cd_driver.c.
Referenced by send_i2c_byte().
#define RESETTIME 30
Definition at line 14 of file I2Cd_driver.c.
Referenced by reset_i2c_bus().
Function Documentation
void i2c_init (void)
Definition at line 28 of file I2Cd_driver.c.
References DELAY10U, ePORTD, ePORTE, ePORTF, GPIO, i2cselected, reset_i2c_bus(), SET_IO_PIN(), and SET_PIN_MODE().
Referenced by ReadTemp().
void i2c_repStart (void)
Definition at line 215 of file I2Cd_driver.c.
References DELAY, DELAY10U, and i2cselected.
Referenced by ReadTemp().
void i2c_start (void)
Definition at line 165 of file I2Cd_driver.c.
References DELAY, DELAY10U, and i2cselected.
Referenced by ReadTemp().
void i2c_stop (void)
Definition at line 265 of file I2Cd_driver.c.
References DELAY10U, and i2cselected.
Referenced by ReadTemp(), and send_i2c_byte().
unsigned char I2CRead (unsigned char address, unsigned char ack)
Definition at line 468 of file I2Cd_driver.c.
References DELAY100U, DELAY10U, i2cselected, read_i2c_byte(), and send_i2c_byte().
Referenced by ReadTemp().
void I2CWrite (unsigned char address, unsigned char i2cWriteData)
Definition at line 457 of file I2Cd_driver.c.
References DELAY10U, and send_i2c_byte().
Referenced by ReadTemp().
unsigned char read_i2c_byte (void)
Definition at line 389 of file I2Cd_driver.c.
References i2cselected.
Referenced by I2CRead().
void reset_i2c_bus (void)
Definition at line 104 of file I2Cd_driver.c.
References DELAY10U, i2cselected, and RESETTIME.
Referenced by i2c_init().
void select_i2c (unsigned char i2c_select_value)
Definition at line 18 of file I2Cd_driver.c.
References i2cselected.
Referenced by ReadTemp().
void send_i2c_byte (unsigned int data)
Definition at line 309 of file I2Cd_driver.c.
References DELAY1U, i2c_stop(), and i2cselected.
Referenced by I2CRead(), and I2CWrite().
Variable Documentation
unsigned char i2cselected = 0
Definition at line 16 of file I2Cd_driver.c.
Referenced by i2c_init(), i2c_repStart(), i2c_start(), i2c_stop(), I2CRead(), read_i2c_byte(), reset_i2c_bus(), select_i2c(), and send_i2c_byte().