AplicationDoc: C:/SVN/00_DEMO/trunk/Firmware/Main/driver/I2Cd_driver.h File Reference
I2Cd_driver.h File Reference
Enumerations
enum I2C_Modul { I2C1 = 1, I2C2 = 2, I2C3 = 3 }
enum ACK { ack = 0, nack = 1 }
Functions
void i2c_init (void)
void i2c_start (void)
void i2c_repStart (void)
void i2c_stop (void)
void send_i2c_byte (unsigned int data)
unsigned char read_i2c_byte (void)
void I2CWrite (unsigned char address, unsigned char i2cWriteData)
unsigned char I2CRead (unsigned char address, unsigned char ack)
void reset_i2c_bus (void)
void select_i2c (unsigned char i2c_select_value)
Enumeration Type Documentation
enum ACK
Enumerator
ack
nack
Definition at line 23 of file I2Cd_driver.h.
enum I2C_Modul
Enumerator
I2C1
I2C2
I2C3
Definition at line 16 of file I2Cd_driver.h.
Function Documentation
void i2c_init (void)
Definition at line 28 of file I2Cd_driver.c.
References DELAY10U, ePORTD, ePORTE, ePORTF, GPIO, i2cselected, reset_i2c_bus(), SET_IO_PIN(), and SET_PIN_MODE().
Referenced by ReadTemp().
void i2c_repStart (void)
Definition at line 215 of file I2Cd_driver.c.
References DELAY, DELAY10U, and i2cselected.
Referenced by ReadTemp().
void i2c_start (void)
Definition at line 165 of file I2Cd_driver.c.
References DELAY, DELAY10U, and i2cselected.
Referenced by ReadTemp().
void i2c_stop (void)
Definition at line 265 of file I2Cd_driver.c.
References DELAY10U, and i2cselected.
Referenced by ReadTemp(), and send_i2c_byte().
unsigned char I2CRead (unsigned char address, unsigned char ack)
Definition at line 468 of file I2Cd_driver.c.
References DELAY100U, DELAY10U, i2cselected, read_i2c_byte(), and send_i2c_byte().
Referenced by ReadTemp().
void I2CWrite (unsigned char address, unsigned char i2cWriteData)
Definition at line 457 of file I2Cd_driver.c.
References DELAY10U, and send_i2c_byte().
Referenced by ReadTemp().
unsigned char read_i2c_byte (void)
Definition at line 389 of file I2Cd_driver.c.
References i2cselected.
Referenced by I2CRead().
void reset_i2c_bus (void)
Definition at line 104 of file I2Cd_driver.c.
References DELAY10U, i2cselected, and RESETTIME.
Referenced by i2c_init().
void select_i2c (unsigned char i2c_select_value)
Definition at line 18 of file I2Cd_driver.c.
References i2cselected.
Referenced by ReadTemp().
void send_i2c_byte (unsigned int data)
Definition at line 309 of file I2Cd_driver.c.
References DELAY1U, i2c_stop(), and i2cselected.
Referenced by I2CRead(), and I2CWrite().