AplicationDoc: C:/SVN/00_DEMO/trunk/Firmware/Main/driver/LEDd_driver.c File Reference
LEDd_driver.c File Reference
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"
#include "LEDd_driver.h"
#include "SPId_driver.h"
#include "Gas_driver.h"
Data Structures
struct GAS_VALUE
Functions
void ReceiveSemaphore_LED (void *pvParameters)
void vReceive_GAS_VALUE ()
unsigned char LED (unsigned short GAS_VAL)
Variables
xQueueHandle ALARM_coada
xSemaphoreHandle Semaph_LED
struct GAS_VALUE xGAS_VALUE
Function Documentation
unsigned char LED (unsigned short GAS_VAL)
Definition at line 119 of file LEDd_driver.c.
References ADC_MAX_VALUE, ePORTB, GAS_VALUE::GAS_Senzor_value, GPIO, OUTPUT, PIN_LED_GREEN, PIN_LED_RED, SET_IO_PIN(), SET_PIN_MODE(), and xGAS_VALUE.
Referenced by vReceive_GAS_VALUE().
void ReceiveSemaphore_LED (void * pvParameters)
Definition at line 56 of file LEDd_driver.c.
References ePORTB, GPIO, OUTPUT, PIN_LED_GREEN, PIN_LED_RED, Semaph_LED, SET_IO_PIN(), SET_PIN_MODE(), and vReceive_GAS_VALUE().
void vReceive_GAS_VALUE (void)
Definition at line 98 of file LEDd_driver.c.
References ALARM_coada, GAS_VALUE::GAS_Senzor_value, LED(), and xGAS_VALUE.
Referenced by ReceiveSemaphore_LED().
Variable Documentation
xQueueHandle ALARM_coada
Definition at line 31 of file LEDd_driver.c.
Referenced by vReceive_GAS_VALUE().
xSemaphoreHandle Semaph_LED
Definition at line 32 of file LEDd_driver.c.
Referenced by ReceiveSemaphore_LED().
struct GAS_VALUE xGAS_VALUE
Referenced by LED(), and vReceive_GAS_VALUE().