AplicationDoc: C:/SVN/00_DEMO/trunk/Firmware/Main/driver/LEDd_driver.h File Reference
LEDd_driver.h File Reference
Macros
#define PIN_LED_GREEN PIN0
#define PIN_LED_RED PIN1
#define ADC_MAX_VALUE 1023
#define _XTAL_FREQ 8000000
Functions
void ReceiveSemaphore_LED (void *pvParameters)
void vReceive_GAS_VALUE (void)
unsigned char LED (unsigned short ADC_fum)
Macro Definition Documentation
#define _XTAL_FREQ 8000000
Definition at line 12 of file LEDd_driver.h.
#define ADC_MAX_VALUE 1023
Definition at line 10 of file LEDd_driver.h.
Referenced by LED().
#define PIN_LED_GREEN PIN0
Definition at line 6 of file LEDd_driver.h.
Referenced by LED(), and ReceiveSemaphore_LED().
#define PIN_LED_RED PIN1
Definition at line 8 of file LEDd_driver.h.
Referenced by LED(), and ReceiveSemaphore_LED().
Function Documentation
unsigned char LED (unsigned short ADC_fum)
Definition at line 119 of file LEDd_driver.c.
References ADC_MAX_VALUE, ePORTB, GAS_VALUE::GAS_Senzor_value, GPIO, OUTPUT, PIN_LED_GREEN, PIN_LED_RED, SET_IO_PIN(), SET_PIN_MODE(), and xGAS_VALUE.
Referenced by vReceive_GAS_VALUE().
void ReceiveSemaphore_LED (void * pvParameters)
Definition at line 56 of file LEDd_driver.c.
References ePORTB, GPIO, OUTPUT, PIN_LED_GREEN, PIN_LED_RED, Semaph_LED, SET_IO_PIN(), SET_PIN_MODE(), and vReceive_GAS_VALUE().
void vReceive_GAS_VALUE (void)
Definition at line 98 of file LEDd_driver.c.
References ALARM_coada, GAS_VALUE::GAS_Senzor_value, LED(), and xGAS_VALUE.
Referenced by ReceiveSemaphore_LED().