AplicationDoc: C:/SVN/00_DEMO/trunk/Firmware/Main/driver/MCP9808d_driver.h File Reference
MCP9808d_driver.h File Reference
Enumerations
enum MCP9808_Pointer_bits {
Read_Only = 0, CONFIG = 1, Tupper = 2, Tlower = 3,
Tcrit = 4, Ta = 5, Manuf_id = 6, Dev_Id = 7,
Resol_reg = 8
}
Functions
float ReadTemp (void)
Enumeration Type Documentation
enum MCP9808_Pointer_bits
Enumerator
Read_Only
CONFIG
Tupper
Tlower
Tcrit
Ta
Manuf_id
Dev_Id
Resol_reg
Definition at line 5 of file MCP9808d_driver.h.
Function Documentation
float ReadTemp (void)
Definition at line 12 of file MCP9808d_driver.c.
References ADDRESSREAD, ADDRESSWRITE, i2c_init(), i2c_repStart(), i2c_start(), i2c_stop(), I2CRead(), I2CWrite(), and select_i2c().