AplicationDoc: C:/SVN/00_DEMO/trunk/Firmware/Main/driver/RTCCd_driver.c File Reference
RTCCd_driver.c File Reference
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"
#include "RTCCd_driver.h"
#include "POWERd_driver.h"
Functions
unsigned short bin2bcd (unsigned short binary_value)
unsigned short bcd2bin (unsigned short bcd_value)
void setRTCTime (unsigned char year, unsigned char month, unsigned char day, unsigned char weekday, unsigned char hour, unsigned char minute, unsigned char second)
RTCTime getRTCTime ()
Function Documentation
unsigned short bcd2bin (unsigned short bcd_value)
Definition at line 64 of file RTCCd_driver.c.
Referenced by getRTCTime().
unsigned short bin2bcd (unsigned short binary_value)
Definition at line 39 of file RTCCd_driver.c.
Referenced by setRTCTime().
RTCTime getRTCTime ()
Definition at line 101 of file RTCCd_driver.c.
References bcd2bin(), _RTCTime::day, _RTCTime::hour, _RTCTime::minute, _RTCTime::month, _RTCTime::second, _RTCTime::weekday, and _RTCTime::year.
void setRTCTime (unsigned char year, unsigned char month, unsigned char day, unsigned char weekday, unsigned char hour, unsigned char minute, unsigned char second)
Definition at line 77 of file RTCCd_driver.c.
References bin2bcd().