AplicationDoc: C:/SVN/00_DEMO/trunk/Firmware/Main/driver/SPId_driver.c File Reference
SPId_driver.c File Reference
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"
#include "p24FJ128GB106.h"
#include "SPId_driver.h"
Functions
void SPId_Init (void)
unsigned char SPId_TXRX (unsigned char data)
void SPI_write (unsigned char slave, unsigned char *data, unsigned char length)
void SPI_read (unsigned char slave, unsigned char *data, unsigned char length)
Function Documentation
void SPI_read (unsigned char slave, unsigned char * data, unsigned char length)
Definition at line 135 of file SPId_driver.c.
References SLAVE1_DISABLE, SLAVE1_ENABLE, SLAVE2_DISABLE, SLAVE2_ENABLE, and SPId_TXRX().
Referenced by read_Flash().
void SPI_write (unsigned char slave, unsigned char * data, unsigned char length)
Definition at line 102 of file SPId_driver.c.
References SLAVE1_DISABLE, SLAVE1_ENABLE, SLAVE2_DISABLE, SLAVE2_ENABLE, and SPId_TXRX().
Referenced by read_Flash(), and write_Flash().
void SPId_Init (void)
Definition at line 62 of file SPId_driver.c.
References CLEAR_BUFFER, CLEAR_IFLAG, CLK_POL_ACTIVE_HIGH, CONFIG_MISO_ENABLE, CONFIG_MOSI_ENABLE, CONFIG_SCLK_ENABLE, CONFIG_SLAVE1_ENABLE, CONFIG_SLAVE2_ENABLE, DISABLE_INTERRUPT, ENABLE_INTERRUPT, ENABLE_SPI, MASTER_ENABLE_ON, PRI_PRESCAL_16_1, RESET_SPI, SEC_PRESCAL_8_1, SLAVE1_DISABLE, SLAVE2_DISABLE, SPI_CKE, and SPI_MODE8_ON.
unsigned char SPId_TXRX (unsigned char data)
Definition at line 91 of file SPId_driver.c.
Referenced by SPI_read(), and SPI_write().