AplicationDoc: C:/SVN/00_DEMO/trunk/Firmware/Main/driver/WDTd_driver.h File Reference
WDTd_driver.h File Reference
Macros
#define RESET RCONbits.SWR
Functions
void Feed (void)
void Reset (void)
int vaTask_Adi (void)
void WDT_Function (void)
Macro Definition Documentation
#define RESET RCONbits.SWR
Definition at line 22 of file WDTd_driver.h.
Referenced by Reset().
Function Documentation
void Feed (void)
Definition at line 90 of file WDTd_driver.c.
References ePORTD, and SET_IO_PIN().
Referenced by WDT_Function().
void Reset (void)
Definition at line 96 of file WDTd_driver.c.
References RESET.
Referenced by WDT_Function().
int vaTask_Adi (void)
void WDT_Function (void)
Definition at line 48 of file WDTd_driver.c.
References ePORTD, Feed(), GPIO, Reset(), SET_IO_PIN(), SET_PIN_MODE(), and vaTask_GAS().